{% set version = "0.1.2" %}
{% set sha256 = "8e3cd8b73e6a248922ac83922d42860fab9122910f1c8d1d3f62514a217776c2" %}

package:
  name: ixmp
  version: {{ version }}

source:
  url: https://github.com/iiasa/ixmp/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - import-timeseries = ixmp.cli:import_timeseries
    - ixmp-config = ixmp.cli:config

requirements:
  build:
    - python
    - pip
  run:
    - openjdk
    - jpype1 >=0.6.2
    - cython
    - numpy
    - pandas
    - nbformat
    - jupyter
    - matplotlib

test:
  imports:
    - ixmp
  commands:
    - import-timeseries -h
    - ixmp-config -h
    - python -c "import ixmp; ixmp.Platform(dbtype='HSQLDB')"

about:
  home: https://github.com/iiasa/ixmp
  license: Apache-2.0
  license_file: LICENSE
  summary: 'The ix modeling platform for integrated and cross-cutting scenario analysis'

extra:
  recipe-maintainers:
    - gidden
