{% set name = "ixmp" %}
{% set version = "3.0.0" %}
{% set hash = "f8786737e41e2fd0896b2c8bd5b777e61404ae5c63a33cbeadbbf8f6f2a6c71a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
  - ixmp = ixmp.cli:main

requirements:
  build:
  - python
  - pip
  - setuptools-scm
  run:
  - click
  - cython
  - dask >=2.14
  - graphviz
  - jpype1 >=0.7.5
  - jupyter
  - matplotlib-base
  - nbformat
  - numpy
  - openjdk
  - pandas >=1.0
  - pint
  - PyYAML
  - xarray
  - xlrd
  - xlsxwriter

test:
  imports:
  - ixmp
  requires:
  - pytest
  commands:
  - python -c "import ixmp; print(ixmp.__version__); assert ixmp.__version__ == '{{ version }}'"
  - ixmp --help

about:
  home: https://github.com/iiasa/ixmp
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    The ix modeling platform for integrated and cross-cutting scenario analysis

extra:
  recipe-maintainers:
  - gidden
  - khaeru
