{% set version = "0.1.1" %}
{% set sha256 = "ceba4a2323bfaa4acfa2cd9fe63c9aa6b76e60f53a6576d2f695f45b281b101c" %}

package:
  name: ixmp
  version: {{ version }}

source:
  url: https://github.com/iiasa/ixmp/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - import-timeseries = ixmp.cli:import_timeseries

requirements:
  build:
    - python
    - pip
  run:
    - openjdk
    - jpype1 >=0.6.2
    - cython
    - numpy
    - pandas
    - nbformat
    - jupyter
    - matplotlib

test:
  imports:
    - ixmp
  commands:
    - import-timeseries -h
    - python -c "import ixmp; ixmp.Platform(dbtype='HSQLDB')"

about:
  home: https://github.com/iiasa/ixmp
  license: Apache-2.0
  license_file: LICENSE
  summary: 'The ix modeling platform for integrated and cross-cutting scenario analysis'

extra:
  recipe-maintainers:
    - gidden
