{% set name = "ixmp" %}
{% set version = "3.5.0" %}
{% set hash = "bb524e519358cba4fd2a5fab3d2a8da8463f1b589a7a5e4794cec67205fe3f39" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - ixmp = ixmp.cli:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-scm

  run:
    - click
    - genno >=1.11.0
    - jpype1 >=1.2.1
    - openjdk
    - openpyxl
    - pandas >=1.2
    - pint
    - python >=3.7
    - PyYAML
    - xarray

test:
  imports:
    - ixmp
  commands:
    - ixmp --help
    - ixmp show-versions

about:
  home: https://github.com/iiasa/ixmp
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    The ix modeling platform for integrated and cross-cutting scenario analysis

extra:
  recipe-maintainers:
    - danielhuppmann
    - khaeru
    - LauWien
    - phackstock
