{% set version = "2.0.0" %}
{% set sha256 = "bb64bebfd3aea0d88e2555a382702e2fdd4c1b6ee013e8d495bb14d3d32f0a7a" %}

package:
  name: ixmp
  version: {{ version }}

source:
  url: https://github.com/iiasa/ixmp/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - ixmp = ixmp.cli:main

requirements:
  build:
    - python
    - pip
  run:
    - click
    - cython
    - dask
    - graphviz
    - jpype1 >=0.7
    - jupyter
    - matplotlib
    - nbformat
    - numpy
    - openjdk
    - pandas
    - pint
    - PyYAML
    - xarray
    - xlrd
    - xlsxwriter

test:
  imports:
    - ixmp
  requires:
    - pytest
  commands:
    - python -c "import ixmp; print(ixmp.__version__); assert ixmp.__version__ == '{{ version }}'"
    - ixmp --help

about:
  home: https://github.com/iiasa/ixmp
  license: Apache-2.0
  license_file: LICENSE
  summary: 'The ix modeling platform for integrated and cross-cutting scenario analysis'

extra:
  recipe-maintainers:
    - gidden
    - khaeru
