{% set version = "0.1.3" %}
{% set sha256 = "d8e2d56079fa869629b4c92311c8719e8036bf85f8680725273f7d4214970809" %}

package:
  name: ixmp
  version: {{ version }}

source:
  url: https://github.com/iiasa/ixmp/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - import-timeseries = ixmp.cli:import_timeseries
    - ixmp-config = ixmp.cli:config

requirements:
  build:
    - python
    - pip
  run:
    - openjdk
    - jpype1 >=0.6.2
    - cython
    - numpy
    - pandas
    - nbformat
    - jupyter
    - matplotlib
    - xlrd
    - xlsxwriter

test:
  imports:
    - ixmp
  commands:
    - python -c "import ixmp; print(ixmp.__version__); assert ixmp.__version__ == '{{ version }}'"
    - import-timeseries -h
    - ixmp-config -h
    - python -c "import ixmp; ixmp.Platform(dbtype='HSQLDB')"

about:
  home: https://github.com/iiasa/ixmp
  license: Apache-2.0
  license_file: LICENSE
  summary: 'The ix modeling platform for integrated and cross-cutting scenario analysis'

extra:
  recipe-maintainers:
    - gidden
    - khaeru
