{% set name = "ixmp" %}
{% set version = "2.0.0" %}
{% set sha256 = "1e1bcc22efc0de4790b9ad37a067f63cba721a2f5846b493dd95cd7292b20f0e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # TODO switch to PyPI after v3.0.0
  url: https://github.com/iiasa/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
  - ixmp = ixmp.cli:main

requirements:
  build:
  - python
  - pip
  run:
  - click
  - cython
  - dask
  - graphviz
  - jpype1 >=0.7
  - jupyter
  - matplotlib-base
  - nbformat
  - numpy
  - openjdk
  - pandas
  - pint
  - PyYAML
  - xarray
  - xlrd
  - xlsxwriter

test:
  imports:
  - ixmp
  requires:
  - pytest
  commands:
  - python -c "import ixmp; print(ixmp.__version__); assert ixmp.__version__ == '{{ version }}'"
  - ixmp --help

about:
  home: https://github.com/iiasa/ixmp
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    The ix modeling platform for integrated and cross-cutting scenario analysis

extra:
  recipe-maintainers:
  - gidden
  - khaeru
