{% set name = "ixmp" %}
{% set version = "3.10.0" %}
{% set hash = "9d4c451a174821680d8f07a9420d669f42799d329837ecb7a5e3dbbb68742016" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - ixmp = ixmp.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools-scm

  run:
    - click
    - genno >=1.16.0
    - jpype1 >=1.2.1
    - openjdk
    - openpyxl
    - pandas >=1.2
    - pint
    - python >={{ python_min }}
    - PyYAML
    - xarray

test:
  requires:
    - python {{ python_min }}
  imports:
    - ixmp
  commands:
    - ixmp --help
    - ixmp show-versions

about:
  home: https://github.com/iiasa/ixmp
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    The ix modeling platform for integrated and cross-cutting scenario analysis

extra:
  recipe-maintainers:
    - danielhuppmann
    - khaeru
    - glatterf42
    - phackstock
