{% set name = "ixmp" %}
{% set version = "3.1.0" %}
{% set hash = "46477b47f1123b3e7c5325bf094843462c0098f3074d63a791fdac3b2a88a6a2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - ixmp = ixmp.cli:main

requirements:
  build:
    - python
    - pip
    - setuptools-scm
  run:
    - click
    - cython
    - dask >=2.14
    - graphviz
    - jpype1 >=0.7.5
    - jupyter
    - matplotlib-base
    - nbformat
    - numpy
    - openjdk
    - pandas >=1.0
    - pint
    - PyYAML
    - xarray
    - xlrd
    - xlsxwriter

test:
  imports:
    - ixmp
  requires:
    - pytest
  commands:
    - ixmp --help

about:
  home: https://github.com/iiasa/ixmp
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    The ix modeling platform for integrated and cross-cutting scenario analysis

extra:
  recipe-maintainers:
    - gidden
    - khaeru
