{% set name = "ixmp" %}
{% set version = "3.4.0" %}
{% set hash = "fc9b2ff843231b993ea8f204d8d9d52f6162049979eeb3a6b0054517c5d67fab" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - ixmp = ixmp.cli:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-scm

  run:
    - click
    - genno >=1.3
    - jpype1 >=1.2.1
    - nbformat
    - numpy
    - openjdk
    - openpyxl
    - pandas >=1.0
    - pint
    - python >=3.6
    - PyYAML
    - xarray

test:
  imports:
    - ixmp
  commands:
    - ixmp --help
    - ixmp show-versions

about:
  home: https://github.com/iiasa/ixmp
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    The ix modeling platform for integrated and cross-cutting scenario analysis

extra:
  recipe-maintainers:
    - danielhuppmann
    - khaeru
    - LauWien
    - phackstock
