travis:
  secure:
    BINSTAR_TOKEN: hJabJup4Lp5Yn7yFTuUGIo8XxocT33S87BMObn6ueI3SfRslHxUG6rmqvjBIZsiFxN8SYQLVmrA74X2mC6j5t+q6sEpS07AsFqcOJzn0TZbrp6eXZQwcpLxdOlsrf/nbJNMaRfVhVMD2PuB9NvgVhVL9ghJhBQWaU9bUZVRh+FAB3fTXDkFkejssFgASog+Af9iEXlajeIc2wFJV31eejIfbUrXOLFIdqYha2mRKZJUoHbJA4cDslWYlAJu6oMLDUMHc6v7yU71+rEfBjBlZBXdD2pLsLHdBrqcZ+Kbe9BSZZfCsdMQxNZ+xxugJDYYyopOEwHZHpt28EeEGbQJQFYWjCoeKmU7C7w//eA4kN7ryNReihCLi+ZUlHuZ3869WSeJ17Xhv8J4e6rb8wPlsu3Mt9qYYA0/rJ72awPfqynv/oRHoJ+8WjGiR+Khja01CmHeoLS9I9zrvTWgV6tLOe3mZ6vSTYTbVEx6E+lq3NQlYvrAdQDP9xXb7dcYsYHteoLHm73crL9EwcWOd8b2cF4BnpXfOYY0moMEhQqvE4VlfiB0iUJ3nTLbJm+T9IrES/xN65N2wKm5O9aVcyWga807vitRdo0h5P3vealw+9MOY7ZTGlewSGzGrX5MioNMzN5O6R0jMQqslk4Rhr7gmrsWg8lhn723XW0AygFVC1fY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
