travis:
  secure:
    BINSTAR_TOKEN: JRLfMGYDQwwBla79mlm3cf9UEk/nu8nyhBaZm6ss5tUJZJvv6ci/6qrrCQuVrXHGMrnigVSq+G+uCi8EdV3qM39GSqY/1swZsC2f86ULjNAYiUq5fhmOQEohiXmErIWsrTUPXaglsEyM31CRDjbBuqeQVLWKi1ACeVvVnPO6CjWchtRjeHw1ukKh8M+c7ym7EzpVfmJrYa3l3azaia5eo9OvtHgJ4I/LuNnbaz2Y9Yn/fOczWxCiKy1dIMQfJHO/ER+1QDd8bGE8pRceBonk5yr8Vfc0hP+Lrcw1VHBlvkCB3Oy0eI0gWLAJyufvDDmfl1eU/3QJJisUryZtQ2hyVNmZdAIUzzD74q7I26vXKLVCTxT1kT5FYYPQxOCD4Z6yRWVXIniKSYuE0ZuuJLjmILz35QMTTYfeJy/G1Rt9Qb3iLzcYrbxdONX9XXoc4PzsYXgpOpm8Yb94fup/fnII40tQ7LGBNjwvFCDRRRUrTYWkf9eTnm4NtiVpGkjjfEis+pf9OpSVI9xM70KgsO+eKdAQKn3vtbWFy71/LSzTXlFWpdKZxoSnQmou2EmZjRUoSTM2IhHNgCykYG3rlTmzNFBpfFDGEYNg7ewwQkY81TujBB1YMBiCXFTMQm0ZCzjtfimg+27gqgK1my0jWyDx7HMjIEH69b66Amlc5Uk2g5k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
